export const FRIEND_GET_SUCCESS = 'FRIEND_GET_SUCCESS';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const SEND_MESSAGES_SUCCESS = 'SEND_MESSAGES_SUCCESS';
export const SOCKET_MESSAGE = 'SOCKET_MESSAGE';
